pool:
  vmImage: ubuntu-latest

stages:
- stage: SCA
  jobs:
  - job: Job
    displayName: 'SCA Dependency check'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - script: find $(Build.SourcesDirectory) -name "*.jar"
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'spring-boot-kubernetes'
        scanPath: '$(Build.SourcesDirectory)/target'
        format: 'JSON'
        reportsDirectory: 'reporte'
    - script: |
        echo "Se analiza el reporte en busca de vulnerabilidades de tipo HIGH o HIGHEST"
        echo "Ubicación del reporte: $(Build.SourcesDirectory)/reporte/dependency-check-report.json"
        if [ $(grep -Po '"confidence":.*?[^\\]",' $(Build.SourcesDirectory)/reporte/dependency-check-report.json | grep '"HIGH"\|"HIGHEST"' | wc -l) -gt 1 ]
        then
          echo "Atención! Hay vulnerabilidades de tipo ALTA (HIGH o HIGHEST)"
          exit 1
        else
          echo "OK! No se encontraron vulnerabilidades de tipo ALTA (HIGH o HIGHEST)"
        fi